if(${BENCHAMEL_BUILD_TSAN})
  add_compile_options(-g -fno-omit-frame-pointer -fsanitize=thread
                      -DVATOMIC_BUILTINS)
  link_libraries(-fsanitize=thread)
endif()

file(GLOB SRCS test/queue/*.c test/spinlock/*.c test/skiplist/*.c)

# OK_name are tests that are correct. They will be marked with an _ok suffix.
# The OK tests are all tests/algorithms not present in the bugs.patch file.
set(OK_arraylock true)
set(OK_cnalock true)
set(OK_hclhlock true)
set(OK_hmcslock true)
set(OK_mcslock true)
set(OK_rec_mcslock true)
set(OK_rec_spinlock true)
set(OK_rec_ticketlock true)
set(OK_rwlock true)
set(OK_semaphore true)
set(OK_ticketlock true)
set(OK_ttaslock true)
set(OK_bounded_mpmc_check_full true)
set(OK_bounded_mpmc_check_empty false)
set(OK_bounded_spsc false)
set(OK_skiplist false)

set(CFLAGS_skiplist)
set(CFLAGS_twalock -DTWA_A=16U)

foreach(SRC ${SRCS})
  get_filename_component(NAME ${SRC} NAME_WLE)
  set(TARGET ${NAME})
  if(${OK_${TARGET}})
    set(TARGET ${TARGET}_ok)
  endif()
  add_executable(${TARGET} ${SRC})
  target_link_libraries(${TARGET} pthread)
  target_include_directories(${TARGET} PRIVATE include)
  target_compile_options(${TARGET} PRIVATE ${CFLAGS_${TARGET}})
endforeach()
