if(POLICY CMP0169)
  cmake_policy(SET CMP0169 OLD)
endif()

if(APPLE)
  message(STATUS "Skipping aget-bug2 on macOS")
else()
  add_subdirectory(aget-bug2)
endif()
add_subdirectory(cherokee-bug1)
add_subdirectory(httrack-3.43.9)
add_subdirectory(memcached-127)
add_subdirectory(pbzip2-0.9.4)
add_subdirectory(stringbuffer-jdk1.4)
add_subdirectory(transmission-1.42)
